sudo: false

language: node_js

node_js:
  - 'lts/*'
cache:
  - yarn

services:
  - postgresql

before_script:
  - psql -c "create database app_db;" -U postgres

script:
  - yarn run test

after_success:
  - yarn run coverage
