sudo: false

language: node_js

node_js:
  - "lts/*"
cache:
  - npm

services:
  - postgresql

before_script:
  - psql -c "create database app_db;" -U postgres

script:
  - npm test

after_success: 
 - npm run coverage